created landing page
acm-ucr/ais-website pull request #17
Opened 2024-07-04 01:38 UTC by zalam007

![image](https://github.com/acm-ucr/AIS-website/assets/146377680/9998025e-9618-475c-8ec0-ac2aec69f2d1)

2024-07-04 02:09 UTC, zalam007 commented
![image](https://github.com/acm-ucr/AIS-website/assets/146377680/9d12ab9a-05f4-449c-8ef6-17977d8cb488)

2024-07-04 23:11 UTC, stormyy00 requested changes

2024-07-04 23:11 UTC, stormyy00 commented on src/components/Landing.jsx
> +    <div className="relative h-screen bg-blue-900 overflow-hidden">
do bg-gradient-to-b from via to, pull from dev for the colors

2024-07-04 23:11 UTC, stormyy00 commented on src/components/Landing.jsx
> +      <div className="absolute bottom-64 right-64 flex flex-col text-white">
use % so bottom-[20%]

2024-07-04 23:11 UTC, stormyy00 commented on src/components/Landing.jsx
> +        <div className="flex items-center mb-8">
try mb-4, looks to high up

2024-07-08 22:29 UTC, zalam007 commented
![image](https://github.com/acm-ucr/AIS-website/assets/146377680/62cc4813-491a-41e6-9763-cd72dc63421e)

2024-07-15 05:48 UTC, zalam007 commented
![Screenshot 2024-07-14 224401](https://github.com/user-attachments/assets/666d6e3e-0947-4574-8767-09ccfadef9ab)

2024-07-15 06:05 UTC, stormyy00 approved these changes

2024-07-15 06:05 UTC, merged